apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-3mgw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-3mgw
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-java-springboot-basic-3mgw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-3mgw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-3mgw
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/my-app-1/devfile-sample-java-springboot-basic-3mgw@sha256:e0f8422ec4fe3535e04f5644cea1addbc132cd4a36855fa05bb4f236df30778b
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
