apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-3mgw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/my-app-1/devfile-sample-java-springboot-basic-3mgw@sha256:78ee03e952c915d44dc671385ef0cb716d219b7f8d6306222872110a1a0adccc
        name: my-java-springboot
        resources: {}
status: {}
